image: Visual Studio 2019
version: '{build}'
branches:
  only:
  - master
skip_tags: true
configuration: Release (Ruby 2.3)
platform:
- x64
- x86
clone_depth: 3
environment:
  SDL2_INCLUDE: C:\SDL2-2.0.12\include
  SDL2_LIB: C:\SDL2-2.0.12\lib\x86
  SDL2_LIB64: C:\SDL2-2.0.12\lib\x64
  DEBUG: true
install:
- ps: >-
    Start-FileDownload https://libsdl.org/release/SDL2-devel-2.0.12-VC.zip
    
    7z x SDL2-devel-2.0.12-VC.zip -oC:\projects\gosu\dependencies
    
    move C:\projects\gosu\dependencies\SDL2-2.0.12 C:\projects\gosu\dependencies\SDL2
test_script:
- ps: >-
    If ($env:PLATFORM -Eq "x64") {
      $env:PATH = "C:\Ruby23-x64\bin;$env:PATH"
    }
    Else {
      $env:PATH = "C:\Ruby23\bin;$env:PATH"
    }
    
    gem install rake rake-compiler minitest --no-doc
    
    cmd /c rake format test TESTOPTS='-v' '2>&1'
