image: Visual Studio 2019
version: '{build}'
branches:
  only:
  - master
skip_tags: true
configuration: Release (Ruby 2.7)
platform:
- x64
- x86
clone_depth: 3
environment:
  DEBUG: true
install:
- ps: >-
    Start-FileDownload https://libsdl.org/release/SDL2-devel-2.0.12-VC.zip
    
    7z x SDL2-devel-2.0.12-VC.zip -oC:\projects\gosu\dependencies
    
    move C:\projects\gosu\dependencies\SDL2-2.0.12 C:\projects\gosu\dependencies\SDL2
test_script:
- ps: >-
    If ($env:PLATFORM -Eq "x64") {
      $env:PATH = "C:\Ruby27-x64\bin;$env:PATH"
    }
    Else {
      $env:PATH = "C:\Ruby27\bin;$env:PATH"
    }
    
    gem install rake rake-compiler minitest --no-doc
    
    cmd /c rake format test TESTOPTS='-v' '2>&1'
